# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

runtime: java
instance_class: F2
env: standard

automatic_scaling:
  max_num_instances: 1

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "17"

env_variables:
  APP_ENV: production
  GCP_DB_USERNAME: $GCP_DB_USERNAME
  GCP_DB_PASSWORD: $GCP_DB_PASSWORD